# whitelist
branches:
  only:
    - master
sudo: required
services:
  - docker
language: java
jdk:
  - openjdk7
before_install:
  #Set up Docker exports
  - export AUTHOR=`git --no-pager show -s --format='%an <%ae>'`
  - export DATE=`TZ=America/New_York date "+%m-%d-%y-%H%M"`
  - export DOCKER_IMAGE="ctrp/ctrp_4x_po"
  - echo "TravisBuild=$TRAVIS_BUILD_NUMBER" > build_number.html &&
        echo "Commit=$TRAVIS_COMMIT" >> build_number.html       &&
        echo "TravisBuildID=$TRAVIS_BUILD_ID" >> build_number.html    &&
        echo "Author=$AUTHOR" >> build_number.html              &&
        echo "BuildTime=$DATE" >> build_number.html             &&
        echo "Docker=$DOCKER_IMAGE:$DATE" >> build_number.html
  - cat ./build_number.html
  #Set others
  - wget https://archive.apache.org/dist/maven/binaries/apache-maven-2.2.1-bin.tar.gz
  - tar xzvf apache-maven-2.2.1-bin.tar.gz
  - rm -rf $HOME/.m2
  - export M2_HOME=`pwd`/apache-maven-2.2.1
  - export M2=$M2_HOME/bin
  - export PATH=$M2:$PATH
  - mvn -v
script:
  ###Build Script for PO
  # - cp build-po/tier-properties/local.properties local.properties
  - cd /home/travis/build/CBIIT/CTRP_4x_PO/build-po
  # - mvn -Dhttps.protocols=TLSv1.1,TLSv1.2 package -e
  #- mvn -Dhttps.protocols=TLSv1.1,TLSv1.2 clean install -e
  - ant -f build-lite.xml dist
  #Build Docker image
  # - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  # - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
after_success:
  # - find ~/.m2/
  # - ls -alth /home/travis/build/CBIIT/CTRP_4x_PO/
  - find /home/travis/build/CBIIT/CTRP_4x_PO/target/
  # - bundle exec codeclimate-test-reporter
    #Build Docker image
  - cd /home/travis/build/CBIIT/CTRP_4x_PO/
  - docker build -t $DOCKER_IMAGE:$DATE -t $DOCKER_IMAGE:latest .
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker images
  - docker push $DOCKER_IMAGE # Pushes both date and latest
  #Deploy to AWS IntTest
  # - docker run -it --rm -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  #   -e AWS_DEFAULT_REGION=us-east-1 silintl/ecs-deploy
  #   --cluster PedMatch-IntTest-Backend --service-name PedMatch-nci-match-patient-api-INTTEST 
  #   -i $DOCKER_IMAGE:$DATE
  #Trigger Travis bdd tests
  # - curl -s -X POST -H "Content-Type:application/json" -H "Accept:application/json" 
  #   -H "Travis-API-Version:3" -H "Authorization:token $TRAVIS_TOKEN" 
  #   -d "{\"request\":{\"message\":\"Triggered by nci-match-patient-api $TRAVIS_COMMIT\", \"branch\":\"master\", \"config\":{\"env\":{\"matrix\":[\"TRIGGER_REPO=nci-match-patient-api;TRIGGER_VER=$DATE;CUC_TAG=@patients;AUTHOR=$AUTHOR\"]}}}}" 
  #   https://api.travis-ci.org/repo/CBIIT%2Fnci-uMatch-bddtests/requests

# after_script:
notifications:
  slack: clinicalbiomed:W5L3wQ69vtL1XJCo8uT3oQgY
