ALTER TABLE CSM_USER ALTER COLUMN LOGIN_NAME TYPE Character Varying(500);
ALTER TABLE CSM_USER ADD COLUMN MIGRATED_FLAG Smallint NOT NULL DEFAULT 0;
ALTER TABLE CSM_USER ADD COLUMN PREMGRT_LOGIN_NAME Character Varying(100);


ALTER TABLE CSM_PG_PE ALTER COLUMN UPDATE_DATE TYPE DATE; 
ALTER TABLE CSM_PG_PE ALTER COLUMN UPDATE_DATE set DEFAULT '1900-01-01';

ALTER TABLE CSM_ROLE_PRIVILEGE DROP COLUMN UPDATE_DATE;
ALTER TABLE CSM_USER_PE DROP COLUMN UPDATE_DATE;

ALTER TABLE CSM_FILTER_CLAUSE RENAME GENERATED_SQL TO GENERATED_SQL_USER;
ALTER TABLE CSM_FILTER_CLAUSE ALTER COLUMN GENERATED_SQL_USER TYPE Character Varying(4000);
ALTER TABLE CSM_FILTER_CLAUSE ALTER COLUMN GENERATED_SQL_USER SET NOT NULL;
ALTER TABLE CSM_FILTER_CLAUSE ADD COLUMN GENERATED_SQL_GROUP Character Varying (4000) NOT NULL;