CREATE SEQUENCE CSM_MAPPING_SEQ
;


CREATE TABLE CSM_MAPPING ( 
       MAPPING_ID int8 not null default nextval('CSM_MAPPING_SEQ'),
       APPLICATION_ID int8 NOT NULL,
       OBJECT_NAME character varying(100) NOT NULL,
       ATTRIBUTE_NAME character varying(100) NOT NULL,
       OBJECT_PACKAGE_NAME character varying(100),
       TABLE_NAME character varying(100),
       TABLE_NAME_GROUP character varying(100),
       TABLE_NAME_USER character varying(100),
       VIEW_NAME_GROUP character varying(100),
       VIEW_NAME_USER character varying(100),
       ACTIVE_FLAG character varying(1) DEFAULT 0,
       MAINTAINED_FLAG character varying(1) DEFAULT 0,
       UPDATE_DATE date NOT NULL default current_date,
       PRIMARY KEY(MAPPING_ID)       
);

ALTER TABLE CSM_MAPPING ADD CONSTRAINT FK_PE_APPLICATION 
FOREIGN KEY (APPLICATION_ID) REFERENCES CSM_APPLICATION (APPLICATION_ID)
ON DELETE CASCADE
;


ALTER TABLE CSM_MAPPING
ADD CONSTRAINT UQ_MP_OBJ_NAME_ATTRI_NAME_APP_ID UNIQUE (OBJECT_NAME,ATTRIBUTE_NAME,APPLICATION_ID)
;

ALTER TABLE CSM_APPLICATION ADD COLUMN CSM_VERSION character varying(20);

CREATE INDEX idx_OBJ_ATTR_APP ON CSM_PROTECTION_ELEMENT
USING btree(OBJECT_ID, ATTRIBUTE, APPLICATION_ID)
;
